### PR TITLE
Populate link_url for non-custom linkTo settings

### LINKED ISSUE #111: Image Widget: Edit screen doesn't pick up file and post links
When images are linked to their file or attachment page, the url to that page never gets passed to the image model, resulting in the edit screen always assuming it's not linked at all.

To reproduce:
1. Select an image
2. For "Link to", either select "Media File" or "Attachment Page".
3. Click "Add to Widget"
4. Click "Edit Image"
5. Check the "Link to" field.

`mediaFrameProps` never get `linkUrl` set when `link` is either "file" or "post".

### PR DESCRIPTION
**Pull request by obenland**
This will properly populate the "Link To" setting in the image widget's edit modal.

The amount of code and its complexity is a poor representation of the time and effort that went into figuring out how to fix this bug. Thanks @westonruter for the guidance.

Fixes #111

### CODE REVIEW

File: wp-admin/js/widgets/media-widgets.js [hunk 1]
```diff
@@ -726,6 +726,12 @@ wp.mediaWidgets = ( function( $ ) {
 				modelProps.height = mediaFrameProps.customHeight;
 			}
 
+			if ( 'post' === mediaFrameProps.link ) {
+				modelProps.link_url = control.selectedAttachment.get( 'link' );
```
Comment (westonruter) [inline wp-admin/js/widgets/media-widgets.js]: This feels a bit “impure” in that we're looking at `control.selectedAttachment` but we're specifically being passed `mediaFrameProps`. I don't suppose `mediaFrameProps.linkUrl` is possible?

Comment (obenland) [reply wp-admin/js/widgets/media-widgets.js]: Good point. Does 49e9e69 look better?

Comment (westonruter) [reply wp-admin/js/widgets/media-widgets.js]: Beautiful

**Review by westonruter — APPROVED** [review]
