### PR TITLE
Harden logic for rendering preview

### LINKED ISSUE #66: When image is deleted, only show 'Select Image' link
When I use an image for the widget from my media library and later delete it, the widget interface correctly shows that the image is missing:

The buttons below the image are incorrect, it should only show 'Select Image' as in the default state of the image when no image is selected:

### PR DESCRIPTION
**Pull request by westonruter**
Moves `error` property from `selectedAttachment` model onto `control.model`, as suggested by @obenland.

Fixes #66.

### CODE REVIEW

File: wp-admin/js/widgets/media-widgets.js [hunk 1]
```diff
@@ -414,11 +399,15 @@ wp.mediaWidgets = ( function( $ ) {
 		/**
 		 * Whether a media item is selected.
 		 *
-		 * @return {boolean} Whether selected.
+		 * @return {boolean} Whether selected and no error.
 		 */
 		isSelected: function isSelected() {
 			var control = this;
 
+			if ( control.model.get( 'error' ) ) {
```
Comment (timmyc) [inline wp-admin/js/widgets/media-widgets.js:407]: I thought I had written some qunit tests around `isSelected` but they must have gotten lost in the shuffle on that PR.  This method, and the changes here, could use some test coverage.  I'd be happy to add that in here on this branch if you'd like.

**Review by obenland — APPROVED** [review]
Tests well!

**Comment by westonruter** [comment]
@timmyc please open a new PR for the qunit test, thanks.
